#!/bin/bash
set -e

PACKAGE=${1}
QUERY='
  query($owner: String!, $repo: String!, $endCursor: String) {
    repository(owner: $owner, name: $repo) {
      vulnerabilityAlerts(first: 100, after: $endCursor) {
        nodes {
          createdAt
          dismissReason
          dismissedAt
          dismisser { login, name }
          securityAdvisory { summary, permalink }
          securityVulnerability {
            package { name }
            severity
          }
          vulnerableManifestPath
          vulnerableRequirements
        },
        pageInfo {
          hasNextPage
          endCursor
        }
      }
    }
  }
'

TEMPLATE="
  {{- tablerow \"PACKAGE\" \"SEVERITY\" \"MANIFEST\" -}}
  {{- range .data.repository.vulnerabilityAlerts.nodes -}}
    {{- if or (not \"${PACKAGE}\") (eq .securityVulnerability.package.name \"${PACKAGE}\") -}}
      {{- if eq .securityVulnerability.severity \"CRITICAL\" -}}
        {{- tablerow .securityVulnerability.package.name (autocolor \"red\" \"critical severity\") .vulnerableManifestPath -}}
      {{- else if eq .securityVulnerability.severity \"HIGH\" -}}
        {{- tablerow .securityVulnerability.package.name (autocolor \"magenta\" \"high severity\") .vulnerableManifestPath -}}
      {{- else if eq .securityVulnerability.severity \"MODERATE\" -}}
        {{- tablerow .securityVulnerability.package.name (autocolor \"yellow\" \"moderate severity\") .vulnerableManifestPath -}}
      {{- else if eq .securityVulnerability.severity \"LOW\" -}}
        {{- tablerow .securityVulnerability.package.name (autocolor \"cyan\" \"low severity\") .vulnerableManifestPath -}}
      {{- end}}
    {{- end}}
  {{- end -}}
"

help() {
    cat <<-EOF
 list your security alerts

USAGE
  $ gh alerts [-h | --help] [<package>]

OPTIONS
  -h, --help    show the help

EXAMPLES
  $ gh alerts pyyaml
  PACKAGE  SEVERITY       MANIFEST
  pyyaml   high severity  requirements.txt
  pyyaml   high severity  requirements.txt
EOF
}

# main
OWNER=":owner"
REPO=":repo"

while [ $# -ge 0 ]; do
    case "$1" in
    -h | --help)
        help
        exit 0
        ;;
    *)
        exec gh api graphql --paginate -F owner="${OWNER}" -F repo="${REPO}" -f query="${QUERY}" --template="${TEMPLATE}"
        exit 0
        ;;
    esac
    shift
done
