#!/usr/bin/env bash
set -e

help() {
    cat <<-EOF
list your open security alerts

USAGE
  $ gh alerts [-h] [-o ORG_NAME] [PACKAGE_NAME]

OPTIONS
  -o ORG_NAME, --org ORG_NAME   show alerts for org
  -h, --help                    show this help message and exit

EXAMPLES
  $ gh alerts pyyaml
  PACKAGE      SEVERITY         MANIFEST             URL
  glob-parent  high severity    package-lock.json    https://github.com/advisories/GHSA-ww39-953v-wcq6
  braces       high severity    package-lock.json    https://github.com/advisories/GHSA-grv7-fg5c-xmjg
  ws           high severity    package-lock.json    https://github.com/advisories/GHSA-3h5v-q93c-6h6q
EOF
}

while [ "$1" != "" ]
do
  case $1 in
    -o | --org ) shift
      OWNER="$1"
      ;;
    -h | --help ) help
      exit 0
      ;;
    * ) PACKAGE="$1"
      ;;
  esac
  shift
done

# shellcheck disable=SC2016  # all $ in the following are not referring to bash variables
QUERY='
  query($owner: String!, $repo: String!, $endCursor: String) {
    repository(owner: $owner, name: $repo) {
      vulnerabilityAlerts(first: 100, after: $endCursor, states: [ OPEN ]) {
        nodes {
          createdAt
          dismissReason
          dismissedAt
          dismisser { login, name }
          securityAdvisory { summary, permalink }
          securityVulnerability {
            package { name }
            severity
          }
          vulnerableManifestPath
          vulnerableRequirements
        },
        pageInfo {
          hasNextPage
          endCursor
        }
      }
    }
  }
'

TEMPLATE="
  {{- range .data.repository.vulnerabilityAlerts.nodes -}}
    {{- if or (not \"${PACKAGE}\") (eq .securityVulnerability.package.name \"${PACKAGE}\") -}}
      {{- if eq .securityVulnerability.severity \"CRITICAL\" -}}
        {{- tablerow .securityVulnerability.package.name (autocolor \"red\" \"critical severity\") .vulnerableManifestPath .securityAdvisory.permalink -}}
      {{- else if eq .securityVulnerability.severity \"HIGH\" -}}
        {{- tablerow .securityVulnerability.package.name (autocolor \"magenta\" \"high severity\") .vulnerableManifestPath .securityAdvisory.permalink -}}
      {{- else if eq .securityVulnerability.severity \"MODERATE\" -}}
        {{- tablerow .securityVulnerability.package.name (autocolor \"yellow\" \"moderate severity\") .vulnerableManifestPath .securityAdvisory.permalink -}}
      {{- else if eq .securityVulnerability.severity \"LOW\" -}}
        {{- tablerow .securityVulnerability.package.name (autocolor \"cyan\" \"low severity\") .vulnerableManifestPath .securityAdvisory.permalink -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
"

# shellcheck disable=SC2016  # all $ in the following are not referring to bash variables
ORG_QUERY='
  query($owner: String!, $endCursor: String) {
    organization (login: $owner) {
      repositories(first: 100, after: $endCursor) {
        nodes {
          vulnerabilityAlerts(first: 100, after: $endCursor, states: [ OPEN ]) {
            nodes {
              createdAt
              dismissReason
              dismissedAt
              dismisser { login, name }
              repository { nameWithOwner }
              securityAdvisory { summary, permalink }
              securityVulnerability {
                package { name }
                severity
              }
              vulnerableManifestPath
              vulnerableRequirements
            }
          }
        },
        pageInfo {
          hasNextPage
          endCursor
        }
      }
    }
  }
'

ORG_TEMPLATE="
  {{- range \$repo := .data.organization.repositories.nodes -}}
    {{- range .vulnerabilityAlerts.nodes -}}
      {{- if or (not \"${PACKAGE}\") (eq .securityVulnerability.package.name \"${PACKAGE}\") -}}
        {{- if eq .securityVulnerability.severity \"CRITICAL\" -}}
          {{- tablerow .repository.nameWithOwner .securityVulnerability.package.name (autocolor \"red\" \"critical severity\") .securityAdvisory.permalink -}}
        {{- else if eq .securityVulnerability.severity \"HIGH\" -}}
          {{- tablerow .repository.nameWithOwner .securityVulnerability.package.name (autocolor \"magenta\" \"high severity\") .securityAdvisory.permalink -}}
        {{- else if eq .securityVulnerability.severity \"MODERATE\" -}}
          {{- tablerow .repository.nameWithOwner .securityVulnerability.package.name (autocolor \"yellow\" \"moderate severity\") .securityAdvisory.permalink -}}
        {{- else if eq .securityVulnerability.severity \"LOW\" -}}
          {{- tablerow .repository.nameWithOwner .securityVulnerability.package.name (autocolor \"cyan\" \"low severity\") .securityAdvisory.permalink -}}
        {{- end -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
"

if [ -n "$OWNER" ]
then
  exec gh api graphql --paginate -F owner="${OWNER}" -f query="${ORG_QUERY}" --template="${ORG_TEMPLATE}"
else
  exec gh api graphql --paginate -F owner=":owner" -F repo=":repo" -f query="${QUERY}" --template="${TEMPLATE}"
fi
